apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: openfaas-fn
  labels:
    app: frontend-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-app
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: serverlessshoppingcart-frontend
        image: serverlessshoppingcart/frontend:latest
        ports:
        - containerPort: 8088
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: openfaas-fn
spec:
  selector:
    app: hello
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: LoadBalancer
