version: 1.0
provider:
  name: openfaas
  gateway: http://127.0.0.1:8080
functions:
  get-products:
    lang: python3-http
    handler: ./get-products
    image: serverlessshoppingcart/get-products:latest
    common_files: true
  get-product:
    lang: python3-http
    handler: ./get-product
    image: serverlessshoppingcart/get-product:latest
    common_files: true
